---
name: Lint

on:
  push:
    branches:
      - main
      - 'integrate**'
      - 'workflow**'
      - 'dev**'

  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          echo "LINT WITH PYLINT ======================="
          pylint exipicrename
      - name: Lint with flake8
        run: |
          echo "LINT WITH FLAKE8 ======================="
          # stop the build if there are Python syntax errors or undefined names
          flake8 exipicrename --count --ignore E402,E501,F401,F403,W503 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 exipicrename --count --exit-zero --max-complexity=14 --ignore E402,F401,F403,W503 --max-line-length=127 --statistics
